export interface Session {
  day: number;
  month: string;
  name: string;
  startTime: string;
  endTime?: string;
}

export interface RaceResult {
  pos: number;
  driverName: string;
  driverSlug: string;
  teamName: string;
  teamColor: string;
  time: string;
  points: number;
}

export interface CircuitInfo {
  name: string;
  image: string; // 서킷 레이아웃 이미지 경로
  length: string;
  firstGrandPrix: number;
  numberOfLaps: number;
  fastestLapTime: string;
  fastestLapHolder: string;
  raceDistance: string;
}

export interface RaceEvent {
  slug: string;
  round: number;
  country: string;
  flag: string;
  raceName: string;
  location: string;
  heroImage: string;
  isCompleted: boolean;
  sessions: Session[];
  circuit: CircuitInfo;
  results?: {
    race?: RaceResult[];
    qualifying?: RaceResult[];
    sprint?: RaceResult[];
  };
}

export const raceEvents: RaceEvent[] = [
  {
    slug: 'australia-2026',
    round: 1,
    country: 'Australia',
    flag: '🇦🇺',
    raceName: 'Australian Grand Prix',
    location: 'Melbourne',
    heroImage: '/circuits/australia.jpg',
    isCompleted: true,
    sessions: [
      { day: 13, month: 'MAR', name: 'PRACTICE 1', startTime: '12:30', endTime: '13:30' },
      { day: 13, month: 'MAR', name: 'PRACTICE 2', startTime: '16:00', endTime: '17:00' },
      { day: 14, month: 'MAR', name: 'PRACTICE 3', startTime: '12:30', endTime: '13:30' },
      { day: 14, month: 'MAR', name: 'QUALIFYING', startTime: '16:00', endTime: '17:00' },
      { day: 15, month: 'MAR', name: 'RACE', startTime: '15:00' },
    ],
    circuit: {
      name: 'Albert Park Circuit',
      image: '/circuits/australia_layout.png',
      length: '5.278km',
      firstGrandPrix: 1996,
      numberOfLaps: 58,
      fastestLapTime: '1:20.235',
      fastestLapHolder: 'Charles Leclerc (2022)',
      raceDistance: '306.124km',
    },
    results: {
      race: [
        { pos: 1, driverName: 'Kimi Antonelli', driverSlug: 'ANT', teamName: 'Mercedes', teamColor: '#00D2BE', time: '1:33:15.607', points: 25 },
        { pos: 2, driverName: 'George Russell', driverSlug: 'RUS', teamName: 'Mercedes', teamColor: '#00D2BE', time: '+5.515s', points: 18 },
        { pos: 3, driverName: 'Lewis Hamilton', driverSlug: 'HAM', teamName: 'Ferrari', teamColor: '#DC0000', time: '+25.267s', points: 15 },
        { pos: 4, driverName: 'Charles Leclerc', driverSlug: 'LEC', teamName: 'Ferrari', teamColor: '#DC0000', time: '+28.894s', points: 12 },
        { pos: 5, driverName: 'Oliver Bearman', driverSlug: 'BEA', teamName: 'Haas', teamColor: '#B6BABD', time: '+57.268s', points: 10 },
        { pos: 6, driverName: 'Lando Norris', driverSlug: 'NOR', teamName: 'McLaren', teamColor: '#FF8000', time: '+1:02.441s', points: 8 },
        { pos: 7, driverName: 'Oscar Piastri', driverSlug: 'PIA', teamName: 'McLaren', teamColor: '#FF8000', time: '+1:15.882s', points: 6 },
        { pos: 8, driverName: 'Max Verstappen', driverSlug: 'VER', teamName: 'Red Bull', teamColor: '#3671C6', time: '+1:28.114s', points: 4 },
        { pos: 9, driverName: 'Fernando Alonso', driverSlug: 'ALO', teamName: 'Aston Martin', teamColor: '#358C75', time: '+1:45.003s', points: 2 },
        { pos: 10, driverName: 'Lance Stroll', driverSlug: 'STR', teamName: 'Aston Martin', teamColor: '#358C75', time: '+1 lap', points: 1 },
        { pos: 11, driverName: 'Pierre Gasly', driverSlug: 'GAS', teamName: 'Alpine', teamColor: '#0093CC', time: '+1 lap', points: 0 },
        { pos: 12, driverName: 'Jack Doohan', driverSlug: 'DOO', teamName: 'Alpine', teamColor: '#0093CC', time: '+1 lap', points: 0 },
        { pos: 13, driverName: 'Yuki Tsunoda', driverSlug: 'TSU', teamName: 'Red Bull', teamColor: '#3671C6', time: '+2 laps', points: 0 },
        { pos: 14, driverName: 'Nico Hülkenberg', driverSlug: 'HUL', teamName: 'Sauber/Audi', teamColor: '#52E252', time: '+2 laps', points: 0 },
        { pos: 15, driverName: 'Gabriel Bortoleto', driverSlug: 'BOR', teamName: 'Sauber/Audi', teamColor: '#52E252', time: '+2 laps', points: 0 },
        { pos: 16, driverName: 'Alex Albon', driverSlug: 'ALB', teamName: 'Williams', teamColor: '#37BEDD', time: 'DNF', points: 0 },
        { pos: 17, driverName: 'Carlos Sainz', driverSlug: 'SAI', teamName: 'Williams', teamColor: '#37BEDD', time: 'DNF', points: 0 },
        { pos: 18, driverName: 'Isack Hadjar', driverSlug: 'HAD', teamName: 'Racing Bulls', teamColor: '#6692FF', time: 'DNF', points: 0 },
        { pos: 19, driverName: 'Liam Lawson', driverSlug: 'LAW', teamName: 'Racing Bulls', teamColor: '#6692FF', time: 'DNF', points: 0 },
        { pos: 20, driverName: 'Esteban Ocon', driverSlug: 'OCO', teamName: 'Haas', teamColor: '#B6BABD', time: 'DNF', points: 0 },
      ],
      qualifying: [
        { pos: 1, driverName: 'Kimi Antonelli', driverSlug: 'ANT', teamName: 'Mercedes', teamColor: '#00D2BE', time: '1:15.096', points: 0 },
        { pos: 2, driverName: 'George Russell', driverSlug: 'RUS', teamName: 'Mercedes', teamColor: '#00D2BE', time: '+0.112s', points: 0 },
        { pos: 3, driverName: 'Charles Leclerc', driverSlug: 'LEC', teamName: 'Ferrari', teamColor: '#DC0000', time: '+0.284s', points: 0 },
        { pos: 4, driverName: 'Lewis Hamilton', driverSlug: 'HAM', teamName: 'Ferrari', teamColor: '#DC0000', time: '+0.391s', points: 0 },
        { pos: 5, driverName: 'Lando Norris', driverSlug: 'NOR', teamName: 'McLaren', teamColor: '#FF8000', time: '+0.512s', points: 0 },
      ],
    },
  },
  {
    slug: 'china-2026',
    round: 2,
    country: 'China',
    flag: '🇨🇳',
    raceName: 'Chinese Grand Prix',
    location: 'Shanghai',
    heroImage: '/circuits/china.jpg',
    isCompleted: true,
    sessions: [
      { day: 20, month: 'MAR', name: 'PRACTICE 1', startTime: '11:30', endTime: '12:30' },
      { day: 20, month: 'MAR', name: 'SPRINT QUALIFYING', startTime: '15:30', endTime: '16:14' },
      { day: 21, month: 'MAR', name: 'SPRINT', startTime: '11:00', endTime: '12:00' },
      { day: 21, month: 'MAR', name: 'QUALIFYING', startTime: '15:00', endTime: '16:00' },
      { day: 22, month: 'MAR', name: 'RACE', startTime: '15:00' },
    ],
    circuit: {
      name: 'Shanghai International Circuit',
      image: '/circuits/china_layout.png',
      length: '5.451km',
      firstGrandPrix: 2004,
      numberOfLaps: 56,
      fastestLapTime: '1:32.238',
      fastestLapHolder: 'Michael Schumacher (2004)',
      raceDistance: '305.066km',
    },
    results: {
      race: [
        { pos: 1, driverName: 'Charles Leclerc', driverSlug: 'LEC', teamName: 'Ferrari', teamColor: '#DC0000', time: '1:31:05.234', points: 25 },
        { pos: 2, driverName: 'Lewis Hamilton', driverSlug: 'HAM', teamName: 'Ferrari', teamColor: '#DC0000', time: '+3.112s', points: 18 },
        { pos: 3, driverName: 'Kimi Antonelli', driverSlug: 'ANT', teamName: 'Mercedes', teamColor: '#00D2BE', time: '+12.445s', points: 15 },
        { pos: 4, driverName: 'George Russell', driverSlug: 'RUS', teamName: 'Mercedes', teamColor: '#00D2BE', time: '+18.771s', points: 12 },
        { pos: 5, driverName: 'Lando Norris', driverSlug: 'NOR', teamName: 'McLaren', teamColor: '#FF8000', time: '+34.882s', points: 10 },
        { pos: 6, driverName: 'Oscar Piastri', driverSlug: 'PIA', teamName: 'McLaren', teamColor: '#FF8000', time: '+41.003s', points: 8 },
        { pos: 7, driverName: 'Max Verstappen', driverSlug: 'VER', teamName: 'Red Bull', teamColor: '#3671C6', time: '+55.114s', points: 6 },
        { pos: 8, driverName: 'Oliver Bearman', driverSlug: 'BEA', teamName: 'Haas', teamColor: '#B6BABD', time: '+1:02.338s', points: 4 },
        { pos: 9, driverName: 'Fernando Alonso', driverSlug: 'ALO', teamName: 'Aston Martin', teamColor: '#358C75', time: '+1:18.556s', points: 2 },
        { pos: 10, driverName: 'Yuki Tsunoda', driverSlug: 'TSU', teamName: 'Red Bull', teamColor: '#3671C6', time: '+1:25.771s', points: 1 },
      ],
    },
  },
  {
    slug: 'japan-2026',
    round: 3,
    country: 'Japan',
    flag: '🇯🇵',
    raceName: 'Japanese Grand Prix',
    location: 'Suzuka',
    heroImage: '/circuits/japan.jpg',
    isCompleted: true,
    sessions: [
      { day: 3, month: 'APR', name: 'PRACTICE 1', startTime: '11:30', endTime: '12:30' },
      { day: 3, month: 'APR', name: 'PRACTICE 2', startTime: '15:00', endTime: '16:00' },
      { day: 4, month: 'APR', name: 'PRACTICE 3', startTime: '11:30', endTime: '12:30' },
      { day: 4, month: 'APR', name: 'QUALIFYING', startTime: '15:00', endTime: '16:00' },
      { day: 5, month: 'APR', name: 'RACE', startTime: '14:00' },
    ],
    circuit: {
      name: 'Suzuka International Racing Course',
      image: '/circuits/japan_layout.png',
      length: '5.807km',
      firstGrandPrix: 1987,
      numberOfLaps: 53,
      fastestLapTime: '1:30.983',
      fastestLapHolder: 'Lewis Hamilton (2019)',
      raceDistance: '307.471km',
    },
    results: {
      race: [
        { pos: 1, driverName: 'Charles Leclerc', driverSlug: 'LEC', teamName: 'Ferrari', teamColor: '#DC0000', time: '1:29:44.112', points: 25 },
        { pos: 2, driverName: 'Kimi Antonelli', driverSlug: 'ANT', teamName: 'Mercedes', teamColor: '#00D2BE', time: '+8.334s', points: 18 },
        { pos: 3, driverName: 'Lewis Hamilton', driverSlug: 'HAM', teamName: 'Ferrari', teamColor: '#DC0000', time: '+15.667s', points: 15 },
        { pos: 4, driverName: 'George Russell', driverSlug: 'RUS', teamName: 'Mercedes', teamColor: '#00D2BE', time: '+22.441s', points: 12 },
        { pos: 5, driverName: 'Lando Norris', driverSlug: 'NOR', teamName: 'McLaren', teamColor: '#FF8000', time: '+38.115s', points: 10 },
      ],
    },
  },
  {
    slug: 'miami-2026',
    round: 4,
    country: 'United States',
    flag: '🇺🇸',
    raceName: 'Miami Grand Prix',
    location: 'Miami',
    heroImage: '/circuits/miami.jpg',
    isCompleted: false,
    sessions: [
      { day: 1, month: 'MAY', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 1, month: 'MAY', name: 'SPRINT QUALIFYING', startTime: '23:30', endTime: '00:14' },
      { day: 2, month: 'MAY', name: 'SPRINT', startTime: '19:00', endTime: '20:00' },
      { day: 2, month: 'MAY', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 3, month: 'MAY', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Miami International Autodrome',
      image: '/circuits/miami_layout.png',
      length: '5.412km',
      firstGrandPrix: 2022,
      numberOfLaps: 57,
      fastestLapTime: '1:29.708',
      fastestLapHolder: 'Max Verstappen (2023)',
      raceDistance: '308.326km',
    },
  },
  {
    slug: 'canada-2026',
    round: 5,
    country: 'Canada',
    flag: '🇨🇦',
    raceName: 'Canadian Grand Prix',
    location: 'Montreal',
    heroImage: '/circuits/canada.jpg',
    isCompleted: false,
    sessions: [
      { day: 22, month: 'MAY', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 22, month: 'MAY', name: 'PRACTICE 2', startTime: '23:00', endTime: '00:00' },
      { day: 23, month: 'MAY', name: 'PRACTICE 3', startTime: '18:30', endTime: '19:30' },
      { day: 23, month: 'MAY', name: 'QUALIFYING', startTime: '22:00', endTime: '23:00' },
      { day: 24, month: 'MAY', name: 'RACE', startTime: '20:00' },
    ],
    circuit: {
      name: 'Circuit Gilles Villeneuve',
      image: '/circuits/canada_layout.png',
      length: '4.361km',
      firstGrandPrix: 1978,
      numberOfLaps: 70,
      fastestLapTime: '1:13.078',
      fastestLapHolder: 'Valtteri Bottas (2019)',
      raceDistance: '305.270km',
    },
  },
  {
    slug: 'monaco-2026',
    round: 6,
    country: 'Monaco',
    flag: '🇲🇨',
    raceName: 'Monaco Grand Prix',
    location: 'Monte Carlo',
    heroImage: '/circuits/monaco.jpg',
    isCompleted: false,
    sessions: [
      { day: 5, month: 'JUN', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 5, month: 'JUN', name: 'PRACTICE 2', startTime: '23:00', endTime: '00:00' },
      { day: 6, month: 'JUN', name: 'PRACTICE 3', startTime: '19:30', endTime: '20:30' },
      { day: 6, month: 'JUN', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 7, month: 'JUN', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Circuit de Monaco',
      image: '/circuits/monaco_layout.png',
      length: '3.337km',
      firstGrandPrix: 1950,
      numberOfLaps: 78,
      fastestLapTime: '1:12.909',
      fastestLapHolder: 'Lewis Hamilton (2021)',
      raceDistance: '260.286km',
    },
  },
  {
    slug: 'barcelona-catalunya-2026',
    round: 7,
    country: 'Spain',
    flag: '🇪🇸',
    raceName: 'Barcelona-Catalunya Grand Prix',
    location: 'Barcelona',
    heroImage: '/circuits/spain.jpg',
    isCompleted: false,
    sessions: [
      { day: 12, month: 'JUN', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 12, month: 'JUN', name: 'PRACTICE 2', startTime: '23:00', endTime: '00:00' },
      { day: 13, month: 'JUN', name: 'PRACTICE 3', startTime: '19:30', endTime: '20:30' },
      { day: 13, month: 'JUN', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 14, month: 'JUN', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Circuit de Barcelona-Catalunya',
      image: '/circuits/spain_layout.png',
      length: '4.657km',
      firstGrandPrix: 1991,
      numberOfLaps: 66,
      fastestLapTime: '1:18.149',
      fastestLapHolder: 'Max Verstappen (2023)',
      raceDistance: '307.236km',
    },
  },
  {
    slug: 'austria-2026',
    round: 8,
    country: 'Austria',
    flag: '🇦🇹',
    raceName: 'Austrian Grand Prix',
    location: 'Spielberg',
    heroImage: '/circuits/austria.jpg',
    isCompleted: false,
    sessions: [
      { day: 26, month: 'JUN', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 26, month: 'JUN', name: 'SPRINT QUALIFYING', startTime: '23:30', endTime: '00:14' },
      { day: 27, month: 'JUN', name: 'SPRINT', startTime: '19:00', endTime: '20:00' },
      { day: 27, month: 'JUN', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 28, month: 'JUN', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Red Bull Ring',
      image: '/circuits/austria_layout.png',
      length: '4.318km',
      firstGrandPrix: 1970,
      numberOfLaps: 71,
      fastestLapTime: '1:05.619',
      fastestLapHolder: 'Carlos Sainz (2020)',
      raceDistance: '306.452km',
    },
  },
  {
    slug: 'great-britain-2026',
    round: 9,
    country: 'Great Britain',
    flag: '🇬🇧',
    raceName: 'British Grand Prix',
    location: 'Silverstone',
    heroImage: '/circuits/great-britain.jpg',
    isCompleted: false,
    sessions: [
      { day: 3, month: 'JUL', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 3, month: 'JUL', name: 'PRACTICE 2', startTime: '23:00', endTime: '00:00' },
      { day: 4, month: 'JUL', name: 'PRACTICE 3', startTime: '19:30', endTime: '20:30' },
      { day: 4, month: 'JUL', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 5, month: 'JUL', name: 'RACE', startTime: '23:00' },
    ],
    circuit: {
      name: 'Silverstone Circuit',
      image: '/circuits/great-britain_layout.png',
      length: '5.891km',
      firstGrandPrix: 1950,
      numberOfLaps: 52,
      fastestLapTime: '1:27.097',
      fastestLapHolder: 'Max Verstappen (2020)',
      raceDistance: '306.198km',
    },
  },
  {
    slug: 'belgium-2026',
    round: 10,
    country: 'Belgium',
    flag: '🇧🇪',
    raceName: 'Belgian Grand Prix',
    location: 'Spa-Francorchamps',
    heroImage: '/circuits/belgium.jpg',
    isCompleted: false,
    sessions: [
      { day: 17, month: 'JUL', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 17, month: 'JUL', name: 'SPRINT QUALIFYING', startTime: '23:30', endTime: '00:14' },
      { day: 18, month: 'JUL', name: 'SPRINT', startTime: '19:00', endTime: '20:00' },
      { day: 18, month: 'JUL', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 19, month: 'JUL', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Circuit de Spa-Francorchamps',
      image: '/circuits/belgium_layout.png',
      length: '7.004km',
      firstGrandPrix: 1950,
      numberOfLaps: 44,
      fastestLapTime: '1:46.286',
      fastestLapHolder: 'Valtteri Bottas (2018)',
      raceDistance: '308.052km',
    },
  },
  {
    slug: 'hungary-2026',
    round: 11,
    country: 'Hungary',
    flag: '🇭🇺',
    raceName: 'Hungarian Grand Prix',
    location: 'Budapest',
    heroImage: '/circuits/hungary.jpg',
    isCompleted: false,
    sessions: [
      { day: 24, month: 'JUL', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 24, month: 'JUL', name: 'PRACTICE 2', startTime: '23:00', endTime: '00:00' },
      { day: 25, month: 'JUL', name: 'PRACTICE 3', startTime: '19:30', endTime: '20:30' },
      { day: 25, month: 'JUL', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 26, month: 'JUL', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Hungaroring',
      image: '/circuits/hungary_layout.png',
      length: '4.381km',
      firstGrandPrix: 1986,
      numberOfLaps: 70,
      fastestLapTime: '1:16.627',
      fastestLapHolder: 'Lewis Hamilton (2020)',
      raceDistance: '306.630km',
    },
  },
  {
    slug: 'netherlands-2026',
    round: 12,
    country: 'Netherlands',
    flag: '🇳🇱',
    raceName: 'Dutch Grand Prix',
    location: 'Zandvoort',
    heroImage: '/circuits/netherlands.jpg',
    isCompleted: false,
    sessions: [
      { day: 21, month: 'AUG', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 21, month: 'AUG', name: 'PRACTICE 2', startTime: '23:00', endTime: '00:00' },
      { day: 22, month: 'AUG', name: 'PRACTICE 3', startTime: '19:30', endTime: '20:30' },
      { day: 22, month: 'AUG', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 23, month: 'AUG', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Circuit Zandvoort',
      image: '/circuits/netherlands_layout.png',
      length: '4.259km',
      firstGrandPrix: 1952,
      numberOfLaps: 72,
      fastestLapTime: '1:11.097',
      fastestLapHolder: 'Lewis Hamilton (2023)',
      raceDistance: '306.587km',
    },
  },
  {
    slug: 'italy-2026',
    round: 13,
    country: 'Italy',
    flag: '🇮🇹',
    raceName: 'Italian Grand Prix',
    location: 'Monza',
    heroImage: '/circuits/italy.jpg',
    isCompleted: false,
    sessions: [
      { day: 4, month: 'SEP', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 4, month: 'SEP', name: 'PRACTICE 2', startTime: '23:00', endTime: '00:00' },
      { day: 5, month: 'SEP', name: 'PRACTICE 3', startTime: '19:30', endTime: '20:30' },
      { day: 5, month: 'SEP', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 6, month: 'SEP', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Autodromo Nazionale Monza',
      image: '/circuits/italy_layout.png',
      length: '5.793km',
      firstGrandPrix: 1950,
      numberOfLaps: 53,
      fastestLapTime: '1:21.046',
      fastestLapHolder: 'Rubens Barrichello (2004)',
      raceDistance: '306.720km',
    },
  },
  {
    slug: 'spain-2026',
    round: 14,
    country: 'Spain',
    flag: '🇪🇸',
    raceName: 'Spanish Grand Prix',
    location: 'Madrid',
    heroImage: '/circuits/spain.jpg',
    isCompleted: false,
    sessions: [
      { day: 11, month: 'SEP', name: 'PRACTICE 1', startTime: '19:30', endTime: '20:30' },
      { day: 11, month: 'SEP', name: 'PRACTICE 2', startTime: '23:00', endTime: '00:00' },
      { day: 12, month: 'SEP', name: 'PRACTICE 3', startTime: '19:30', endTime: '20:30' },
      { day: 12, month: 'SEP', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 13, month: 'SEP', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Madrid Street Circuit',
      image: '/circuits/spain_madrid_layout.png',
      length: '5.473km',
      firstGrandPrix: 2026,
      numberOfLaps: 56,
      fastestLapTime: 'TBD',
      fastestLapHolder: 'TBD',
      raceDistance: '306.488km',
    },
  },
  {
    slug: 'azerbaijan-2026',
    round: 15,
    country: 'Azerbaijan',
    flag: '🇦🇿',
    raceName: 'Azerbaijan Grand Prix',
    location: 'Baku',
    heroImage: '/circuits/azerbaijan.jpg',
    isCompleted: false,
    sessions: [
      { day: 24, month: 'SEP', name: 'PRACTICE 1', startTime: '18:30', endTime: '19:30' },
      { day: 24, month: 'SEP', name: 'PRACTICE 2', startTime: '22:00', endTime: '23:00' },
      { day: 25, month: 'SEP', name: 'PRACTICE 3', startTime: '18:30', endTime: '19:30' },
      { day: 25, month: 'SEP', name: 'QUALIFYING', startTime: '22:00', endTime: '23:00' },
      { day: 26, month: 'SEP', name: 'RACE', startTime: '20:00' },
    ],
    circuit: {
      name: 'Baku City Circuit',
      image: '/circuits/azerbaijan_layout.png',
      length: '6.003km',
      firstGrandPrix: 2016,
      numberOfLaps: 51,
      fastestLapTime: '1:43.009',
      fastestLapHolder: 'Charles Leclerc (2019)',
      raceDistance: '306.049km',
    },
  },
  {
    slug: 'singapore-2026',
    round: 16,
    country: 'Singapore',
    flag: '🇸🇬',
    raceName: 'Singapore Grand Prix',
    location: 'Marina Bay',
    heroImage: '/circuits/singapore.jpg',
    isCompleted: false,
    sessions: [
      { day: 9, month: 'OCT', name: 'PRACTICE 1', startTime: '17:30', endTime: '18:30' },
      { day: 9, month: 'OCT', name: 'PRACTICE 2', startTime: '21:00', endTime: '22:00' },
      { day: 10, month: 'OCT', name: 'PRACTICE 3', startTime: '17:30', endTime: '18:30' },
      { day: 10, month: 'OCT', name: 'QUALIFYING', startTime: '21:00', endTime: '22:00' },
      { day: 11, month: 'OCT', name: 'RACE', startTime: '21:00' },
    ],
    circuit: {
      name: 'Marina Bay Street Circuit',
      image: '/circuits/singapore_layout.png',
      length: '4.940km',
      firstGrandPrix: 2008,
      numberOfLaps: 62,
      fastestLapTime: '1:35.867',
      fastestLapHolder: 'Lewis Hamilton (2023)',
      raceDistance: '306.143km',
    },
  },
  {
    slug: 'united-states-2026',
    round: 17,
    country: 'United States',
    flag: '🇺🇸',
    raceName: 'United States Grand Prix',
    location: 'Austin',
    heroImage: '/circuits/usa.jpg',
    isCompleted: false,
    sessions: [
      { day: 23, month: 'OCT', name: 'PRACTICE 1', startTime: '02:30', endTime: '03:30' },
      { day: 23, month: 'OCT', name: 'SPRINT QUALIFYING', startTime: '06:30', endTime: '07:14' },
      { day: 24, month: 'OCT', name: 'SPRINT', startTime: '02:00', endTime: '03:00' },
      { day: 24, month: 'OCT', name: 'QUALIFYING', startTime: '06:00', endTime: '07:00' },
      { day: 25, month: 'OCT', name: 'RACE', startTime: '04:00' },
    ],
    circuit: {
      name: 'Circuit of the Americas',
      image: '/circuits/usa_layout.png',
      length: '5.513km',
      firstGrandPrix: 2012,
      numberOfLaps: 56,
      fastestLapTime: '1:36.169',
      fastestLapHolder: 'Charles Leclerc (2019)',
      raceDistance: '308.405km',
    },
  },
  {
    slug: 'mexico-2026',
    round: 18,
    country: 'Mexico',
    flag: '🇲🇽',
    raceName: 'Mexico City Grand Prix',
    location: 'Mexico City',
    heroImage: '/circuits/mexico.jpg',
    isCompleted: false,
    sessions: [
      { day: 30, month: 'OCT', name: 'PRACTICE 1', startTime: '03:30', endTime: '04:30' },
      { day: 30, month: 'OCT', name: 'PRACTICE 2', startTime: '07:00', endTime: '08:00' },
      { day: 31, month: 'OCT', name: 'PRACTICE 3', startTime: '03:30', endTime: '04:30' },
      { day: 31, month: 'OCT', name: 'QUALIFYING', startTime: '07:00', endTime: '08:00' },
      { day: 1, month: 'NOV', name: 'RACE', startTime: '06:00' },
    ],
    circuit: {
      name: 'Autódromo Hermanos Rodríguez',
      image: '/circuits/mexico_layout.png',
      length: '4.304km',
      firstGrandPrix: 1963,
      numberOfLaps: 71,
      fastestLapTime: '1:17.774',
      fastestLapHolder: 'Valtteri Bottas (2021)',
      raceDistance: '305.354km',
    },
  },
  {
    slug: 'brazil-2026',
    round: 19,
    country: 'Brazil',
    flag: '🇧🇷',
    raceName: 'São Paulo Grand Prix',
    location: 'São Paulo',
    heroImage: '/circuits/brazil.jpg',
    isCompleted: false,
    sessions: [
      { day: 6, month: 'NOV', name: 'PRACTICE 1', startTime: '00:30', endTime: '01:30' },
      { day: 6, month: 'NOV', name: 'SPRINT QUALIFYING', startTime: '04:30', endTime: '05:14' },
      { day: 7, month: 'NOV', name: 'SPRINT', startTime: '00:00', endTime: '01:00' },
      { day: 7, month: 'NOV', name: 'QUALIFYING', startTime: '04:00', endTime: '05:00' },
      { day: 8, month: 'NOV', name: 'RACE', startTime: '03:00' },
    ],
    circuit: {
      name: 'Autódromo José Carlos Pace',
      image: '/circuits/brazil_layout.png',
      length: '4.309km',
      firstGrandPrix: 1973,
      numberOfLaps: 71,
      fastestLapTime: '1:10.540',
      fastestLapHolder: 'Valtteri Bottas (2018)',
      raceDistance: '305.879km',
    },
  },
  {
    slug: 'las-vegas-2026',
    round: 20,
    country: 'United States',
    flag: '🇺🇸',
    raceName: 'Las Vegas Grand Prix',
    location: 'Las Vegas',
    heroImage: '/circuits/las-vegas.jpg',
    isCompleted: false,
    sessions: [
      { day: 19, month: 'NOV', name: 'PRACTICE 1', startTime: '11:30', endTime: '12:30' },
      { day: 19, month: 'NOV', name: 'PRACTICE 2', startTime: '15:00', endTime: '16:00' },
      { day: 20, month: 'NOV', name: 'PRACTICE 3', startTime: '11:30', endTime: '12:30' },
      { day: 20, month: 'NOV', name: 'QUALIFYING', startTime: '15:00', endTime: '16:00' },
      { day: 21, month: 'NOV', name: 'RACE', startTime: '15:00' },
    ],
    circuit: {
      name: 'Las Vegas Strip Circuit',
      image: '/circuits/las-vegas_layout.png',
      length: '6.201km',
      firstGrandPrix: 2023,
      numberOfLaps: 50,
      fastestLapTime: '1:35.490',
      fastestLapHolder: 'Oscar Piastri (2024)',
      raceDistance: '310.050km',
    },
  },
  {
    slug: 'qatar-2026',
    round: 21,
    country: 'Qatar',
    flag: '🇶🇦',
    raceName: 'Qatar Grand Prix',
    location: 'Lusail',
    heroImage: '/circuits/qatar.jpg',
    isCompleted: false,
    sessions: [
      { day: 27, month: 'NOV', name: 'PRACTICE 1', startTime: '20:30', endTime: '21:30' },
      { day: 27, month: 'NOV', name: 'SPRINT QUALIFYING', startTime: '00:30', endTime: '01:14' },
      { day: 28, month: 'NOV', name: 'SPRINT', startTime: '20:00', endTime: '21:00' },
      { day: 28, month: 'NOV', name: 'QUALIFYING', startTime: '00:00', endTime: '01:00' },
      { day: 29, month: 'NOV', name: 'RACE', startTime: '00:00' },
    ],
    circuit: {
      name: 'Lusail International Circuit',
      image: '/circuits/qatar_layout.png',
      length: '5.419km',
      firstGrandPrix: 2021,
      numberOfLaps: 57,
      fastestLapTime: '1:24.319',
      fastestLapHolder: 'Max Verstappen (2023)',
      raceDistance: '308.611km',
    },
  },
  {
    slug: 'abu-dhabi-2026',
    round: 22,
    country: 'Abu Dhabi',
    flag: '🇦🇪',
    raceName: 'Abu Dhabi Grand Prix',
    location: 'Yas Marina',
    heroImage: '/circuits/abu-dhabi.jpg',
    isCompleted: false,
    sessions: [
      { day: 4, month: 'DEC', name: 'PRACTICE 1', startTime: '18:30', endTime: '19:30' },
      { day: 4, month: 'DEC', name: 'PRACTICE 2', startTime: '22:00', endTime: '23:00' },
      { day: 5, month: 'DEC', name: 'PRACTICE 3', startTime: '19:30', endTime: '20:30' },
      { day: 5, month: 'DEC', name: 'QUALIFYING', startTime: '23:00', endTime: '00:00' },
      { day: 6, month: 'DEC', name: 'RACE', startTime: '22:00' },
    ],
    circuit: {
      name: 'Yas Marina Circuit',
      image: '/circuits/abu-dhabi_layout.png',
      length: '5.281km',
      firstGrandPrix: 2009,
      numberOfLaps: 58,
      fastestLapTime: '1:26.103',
      fastestLapHolder: 'Max Verstappen (2021)',
      raceDistance: '306.183km',
    },
  },
];
